version: '3.8'

services:
  # Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ai-agent-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ai-agent-network

  # AI Agent Framework
  agent:
    build: .
    container_name: ai-agent-framework
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - LOG_LEVEL=info
      - BROWSER_HEADLESS=true
      - MEMORY_TYPE=memory
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ai-agent-network
    volumes:
      - /dev/shm:/dev/shm  # Shared memory for browser

  # Optional: Redis for distributed memory (can be enabled later)
  redis:
    image: redis:7-alpine
    container_name: ai-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ai-agent-network
    profiles:
      - redis  # Only start with --profile redis

volumes:
  ollama_data:
    driver: local
  redis_data:
    driver: local

networks:
  ai-agent-network:
    driver: bridge
